Upgrade to latest version to AWS S3 SDK (1.12.127)
This should resolve an issue of SDK accessing private sun API
and failing to open modules on Java 16+

java.lang.reflect.InaccessibleObjectException: Unable to make javax.crypto.SecretKey sun.security.ssl.SSLSessionImpl.getMasterSecret() accessible: module java.base does not "opens sun.security.ssl" to unnamed module @34033bd0
[2021-12-10T07:33:43.288Z] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[2021-12-10T07:33:43.288Z] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[2021-12-10T07:33:43.288Z] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[2021-12-10T07:33:43.288Z] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[2021-12-10T07:33:43.288Z] 	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.verifyMasterSecret(SdkTLSSocketFactory.java:186)
[2021-12-10T07:33:43.288Z] 	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:128)