Fix race condition in Model::adaptTestForTrain
This race condition occurs when doing PDP calculation during
StackedEnsemble's metalearner (GLM) scoring.

Stack Trace:
java.lang.RuntimeException: java.lang.AssertionError
	at water.Futures.blockForPending(Futures.java:88)
	at
hex.PartialDependence$PartialDependenceDriver.compute2(PartialDependence.java:263)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1563)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at
jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
Caused by: java.lang.AssertionError
	at water.util.IcedHashMapBase.put(IcedHashMapBase.java:69)
	at hex.Model.adaptTestForTrain(Model.java:1424)
	at hex.Model.adaptTestForTrain(Model.java:1300)
	at hex.Model.score(Model.java:1588)
	at
hex.ensemble.StackedEnsembleModel.predictScoreImpl(StackedEnsembleModel.java:172)
	at hex.Model.score(Model.java:1599)
	at hex.Model.score(Model.java:1582)
	at
hex.PartialDependence$PartialDependenceDriver$CalculatePdpPerBin.compute2(PartialDependence.java:400)
	... 6 more