[PUBDEV-4017][HOTFIX] :fire: Fix the build dependencies. (#801)
* [PUBDEV-4017][HOTFIX] Fix the build dependencies.

Wrong version of Download Task Plugin was used for new gradle version causing
```
java.lang.NoClassDefFoundError: Lorg/gradle/logging/ProgressLogger
```

The fix:
  - upgrade version of download-task-plugin
  - fix collision of buildscript dependencies by updating minio version and forcing http-client version to 4.5.2
  - minor update in `gradle/s3sync.gradle` script to include dependencies directly in the script instead of top-level script

* Adding missing file

* Fix setup of scalac memory requirements.

* Add missing joda to s3sync build script