change the tolerance on stddev in pca test from 1e-5 to 1e-4 intermittent failure like this shows 1e-5 isn't met but 1e-4 should be? Caused by: java.lang.RuntimeException: java.lang.AssertionError: expected:<202.7230564> but was:<202.72300755074707>     at hex.pca.PCATest.testArrestsScoring(PCATest.java:183)     ... 35 more Caused by: java.lang.AssertionError: expected:<202.7230564> but was:<202.72300755074707>     at org.junit.Assert.fail(Assert.java:88)     at org.junit.Assert.failNotEquals(Assert.java:743)     at org.junit.Assert.assertEquals(Assert.java:494)     at org.junit.Assert.assertEquals(Assert.java:592)     at hex.pca.PCATest.checkStddev(PCATest.java:25)     at hex.pca.PCATest.testArrestsScoring(PCATest.java:175)